source 'https://rubygems.org'

# Added when I created the app

gem 'coffee-rails', '~> 4.0.0'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'rails', '4.1.1'
gem 'sass-rails', '~> 4.0.3'
gem 'sdoc', '~> 0.4.0',         group: :doc
gem 'spring',                   group: :development
gem 'sqlite3'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

# Added by me

gem 'neat'

# Notes generated when I created the app

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer',  platforms: :ruby

# Use jquery as the JavaScript library
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# bundle exec rake doc:rails generates the API under doc/api.

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

